name: LXC Compile

on:
  # Allow to trigger action manually
  workflow_dispatch:

jobs:
  build_lxc:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: apt-get update && apt-get -y install git make pkg-config libdevmapper-dev libseccomp-dev libbtrfs-dev jq meson libdbus-1-dev docbook2x libpam0g-dev ninja-build pkg-config libcap-dev libseccomp-dev libselinux1-dev gcc xz-utils

    - name: Compile LXC
      run: |
        # Get LXC version and create necessary directories
        LXC_V=$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/lxc/lxc/releases/latest | jq -r '.tag_name')
        BUILDDIR=${{ github.workspace }}/$LXC_V
        PACKAGEDIR=$BUILDDIR/lxc_package
        mkdir -p $PACKAGEDIR/DEBIAN $PACKAGEDIR/usr/share/doc/mos-lxc

        # Add initial copyright to package dir:
        echo -e "This package contains software under various licenses.\nSee the following files for details:\n" > $PACKAGEDIR/usr/share/doc/mos-lxc/copyright

        # LXC
        cd $BUILDDIR
        git clone --branch $LXC_V --single-branch --depth 1 https://github.com/lxc/lxc
        cd $BUILDDIR/lxc
        meson setup -Dprefix=/usr \
          --libdir=/usr/lib/x86_64-linux-gnu \
          -Dsysconfdir=/etc \
          -Dprefix=/usr \
          -Dwerror=false \
          -Dapparmor=false \
          -Dselinux=false \
          -Dpam-cgroup=true \
          -Dinit-script=sysvinit \
          build

        meson compile -C build

        DESTDIR=$PACKAGEDIR make install -j20

        rm -rf $PACKAGEDIR/etc/init.d/* $PACKAGEDIR/usr/include $PACKAGEDIR/usr/lib/x86_64-linux-gnu/liblxc.a $PACKAGEDIR/usr/lib/x86_64-linux-gnu/pkgconfig

        # Add Licenses to copyright
        cp ${{ github.workspace }}/LICENSE $PACKAGEDIR/usr/share/doc/mos-lxc/LICENSE
        echo -e "- LICENSE: License for packaging scripts" >> $PACKAGEDIR/usr/share/doc/mos-lxc/copyright
        cp $BUILDDIR/lxc/LICENSE.GPL2 $PACKAGEDIR/usr/share/doc/mos-lxc/LICENSE.GPL2-lxc
        echo -e "- LICENSE.GPL2-lxc: License for lxc components" >> $PACKAGEDIR/usr/share/doc/mos-lxc/copyright
        cp $BUILDDIR/lxc/LICENSE.LGPL2.1 $PACKAGEDIR/usr/share/doc/mos-lxc/LICENSE.LGPL2.1-lxc
        echo -e "- LICENSE.LGPL2.1-lxc: License for lxc components" >> $PACKAGEDIR/usr/share/doc/mos-lxc/copyright

        cp ${{ github.workspace }}/etc/init.d/lxc $PACKAGEDIR/etc/init.d/lxc
        cp ${{ github.workspace }}/etc/init.d/lxc-net $PACKAGEDIR/etc/init.d/lxc-net

        cat > $PACKAGEDIR/DEBIAN/control << EOF
        Package: LXC
        Version: ${LXC_V#v}-mos
        Architecture: amd64
        Maintainer: admin@minenet.at
        Description: Custom LXC build for MOS
        EOF

        cd $BUILDDIR
        chmod -R 755 $PACKAGEDIR
        dpkg-deb --build lxc_package mos-lxc_${LXC_V#v}_amd64.deb
        md5sum $BUILDDIR/mos-lxc_${LXC_V#v}_amd64.deb | awk '{print $1}' > $BUILDDIR/mos-lxc_${LXC_V#v}_amd64.deb.md5

        echo "LXC_V=${LXC_V#v}
        BUILDDIR=$BUILDDIR" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.LXC_V }}
        release_name: "LXC ${{ env.LXC_V }}"
        body: |
          This is the custom Debian package from LXC for MOS

          ### Package contents:
          - [lxc](https://github.com/lxc/lxc) v${{ env.LXC_V }}
        draft: false
        prerelease: false

    - name: Upload deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-lxc_${{ env.LXC_V }}_amd64.deb
        asset_name: mos-lxc_${{ env.LXC_V }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload md5 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.BUILDDIR }}/mos-lxc_${{ env.LXC_V }}_amd64.deb.md5
        asset_name: mos-lxc_${{ env.LXC_V }}_amd64.deb.md5
        asset_content_type: text/plain

    - name: Set notification variables on success
      if: success()
      run: |
        echo "NOTIFICATION_PRIORITY=0" >> $GITHUB_ENV
        echo "NOTIFICATION_MESSAGE=Built LXC v${{ env.LXC_V }}" >> $GITHUB_ENV

    - name: Set notification variables on failure
      if: failure()
      run: |
        echo "NOTIFICATION_PRIORITY=1" >> $GITHUB_ENV
        echo "NOTIFICATION_MESSAGE=Failed to build LXC v${{ env.LXC_V }}" >> $GITHUB_ENV

    - name: Cleanup & Notification
      if: always()
      run: |
        # Discord notification function
        discord_push_notification() {
          if [ $3 -ge 1 ]; then
            COLOR=16711680
          else
            COLOR=65280
          fi

          data=$(cat <<EOF
        {
          "embeds": [{
            "title": "${1}",
            "description": "${2}",
            "color": ${COLOR}
          }]
        }
        EOF
        )
          curl -H "Content-Type: application/json" -d "$data" "${{ secrets.DISCORD_WEBHOOK_URL }}"
        }

        discord_push_notification "${{ github.workflow }}" "${{ env.NOTIFICATION_MESSAGE }}" "${{ env.NOTIFICATION_PRIORITY }}"
        rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.*
